apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  releaseName: zigbee2mqtt
  chart:
    spec:
      chart: zigbee2mqtt
      sourceRef:
        kind: HelmRepository
        name: zigbee2mqtt
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    # Required: MQTT settings
    zigbee2mqtt:
      mqtt:
        # Required: MQTT server URL (use mqtts:// for SSL/TLS connection)
        server: "mqtts://192.168.1.45:31884"
        # Optional: MQTT server authentication user (default: nothing)
        user: admin
        # Optional: MQTT server authentication password (default: nothing)
        password: admin@123
        # Optional: disable self-signed SSL certificates (default: true)
        reject_unauthorized: false
      serial:
        port: tcp://192.168.1.53:6638
