# Avahi DaemonSet - runs on all nodes with hostNetwork
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: avahi-daemon
  namespace: home-automation
  labels:
    app: avahi
spec:
  selector:
    matchLabels:
      app: avahi
  template:
    metadata:
      labels:
        app: avahi
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: avahi
          image: flungo/avahi:latest
          env:
            - name: AVAHI_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
